#include "wannaviewer/resolvers/BrowserEmbedResolver.hpp"

#include <windows.h>
#include <unknwn.h>
#include <WebView2.h>
#include <WebView2EnvironmentOptions.h>
#include <wrl.h>

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cctype>
#include <cwctype>
#include <filesystem>
#include <format>
#include <optional>
#include <string>
#include <string_view>
#include <utility>

namespace wannaviewer {
namespace {

using Microsoft::WRL::Callback;
using Microsoft::WRL::ComPtr;

constexpr auto kResolutionTimeout = std::chrono::seconds(45);
constexpr auto kCandidateSettleTime = std::chrono::seconds(2);

std::filesystem::path SessionProfilePath(const std::filesystem::path& root) {
    static std::atomic_uint64_t counter{0};
    return root / std::format("session-{}-{}-{}", GetCurrentProcessId(), GetTickCount64(), counter.fetch_add(1));
}

class ScopedProfileFolder final {
public:
    explicit ScopedProfileFolder(std::filesystem::path path) : path_(std::move(path)) {}
    ~ScopedProfileFolder() {
        for (unsigned attempt = 0; attempt < 10; ++attempt) {
            std::error_code error;
            std::filesystem::remove_all(path_, error);
            if (!std::filesystem::exists(path_, error)) return;
            Sleep(50);
        }
    }
    ScopedProfileFolder(const ScopedProfileFolder&) = delete;
    ScopedProfileFolder& operator=(const ScopedProfileFolder&) = delete;

private:
    std::filesystem::path path_;
};

std::wstring Utf8ToWide(std::string_view value) {
    if (value.empty()) return {};
    const int count = MultiByteToWideChar(CP_UTF8, MB_ERR_INVALID_CHARS, value.data(),
                                          static_cast<int>(value.size()), nullptr, 0);
    if (count <= 0) return {};
    std::wstring result(static_cast<std::size_t>(count), L'\0');
    if (MultiByteToWideChar(CP_UTF8, MB_ERR_INVALID_CHARS, value.data(), static_cast<int>(value.size()),
                            result.data(), count) != count) return {};
    return result;
}

std::string WideToUtf8(std::wstring_view value) {
    if (value.empty()) return {};
    const int count = WideCharToMultiByte(CP_UTF8, WC_ERR_INVALID_CHARS, value.data(),
                                          static_cast<int>(value.size()), nullptr, 0, nullptr, nullptr);
    if (count <= 0) return {};
    std::string result(static_cast<std::size_t>(count), '\0');
    if (WideCharToMultiByte(CP_UTF8, WC_ERR_INVALID_CHARS, value.data(), static_cast<int>(value.size()),
                            result.data(), count, nullptr, nullptr) != count) return {};
    return result;
}

std::string Lower(std::string value) {
    std::ranges::transform(value, value.begin(), [](unsigned char character) {
        return static_cast<char>(std::tolower(character));
    });
    return value;
}

std::wstring Lower(std::wstring value) {
    std::ranges::transform(value, value.begin(), [](wchar_t character) {
        return static_cast<wchar_t>(std::towlower(character));
    });
    return value;
}

std::wstring JavaScriptString(std::string_view utf8) {
    const auto value = Utf8ToWide(utf8);
    std::wstring result = L"\"";
    result.reserve(value.size() + 2);
    for (const wchar_t character : value) {
        switch (character) {
        case L'\\': result += L"\\\\"; break;
        case L'\"': result += L"\\\""; break;
        case L'\r': result += L"\\r"; break;
        case L'\n': result += L"\\n"; break;
        case L'\t': result += L"\\t"; break;
        default:
            if (character < 0x20) result += std::format(L"\\u{:04X}", static_cast<unsigned>(character));
            else result.push_back(character);
            break;
        }
    }
    result.push_back(L'\"');
    return result;
}

std::string RefererFrom(const ResolveContext& context) {
    for (const auto& [name, value] : context.requestHeaders)
        if (Lower(name) == "referer") return value;
    return {};
}

bool IsAllowedReferer(const Url& url) {
    return url.IsHttps() && !url.IsPrivateHostLiteral() &&
           (url.HostIs("yummyani.me") || url.HostIs("yummyanime.tv") || url.HostIs("animego.me"));
}

bool IsAllowedHeader(std::string_view lowerName) {
    // Reproduce the provider's media request, including provider-defined
    // authorization fields and browser fetch metadata. Hop-by-hop/framing and
    // compression headers must be regenerated by libmpv's HTTP stack.
    return !lowerName.empty() && lowerName.front() != ':' &&
           lowerName != "host" && lowerName != "connection" && lowerName != "proxy-connection" &&
           lowerName != "content-length" && lowerName != "transfer-encoding" && lowerName != "te" &&
           lowerName != "trailer" && lowerName != "upgrade" && lowerName != "accept-encoding" &&
           lowerName != "expect" && !lowerName.starts_with("access-control-request-");
}

HeaderMap ReadPlaybackHeaders(ICoreWebView2WebResourceRequest* request) {
    HeaderMap result;
    ComPtr<ICoreWebView2HttpRequestHeaders> headers;
    if (!request || FAILED(request->get_Headers(&headers)) || !headers) return result;
    ComPtr<ICoreWebView2HttpHeadersCollectionIterator> iterator;
    if (FAILED(headers->GetIterator(&iterator)) || !iterator) return result;
    BOOL hasCurrent = FALSE;
    if (FAILED(iterator->get_HasCurrentHeader(&hasCurrent))) return result;
    while (hasCurrent) {
        LPWSTR name = nullptr;
        LPWSTR value = nullptr;
        if (SUCCEEDED(iterator->GetCurrentHeader(&name, &value)) && name && value) {
            auto utf8Name = WideToUtf8(name);
            auto utf8Value = WideToUtf8(value);
            if (IsAllowedHeader(Lower(utf8Name)) && !utf8Value.empty())
                result.insert_or_assign(std::move(utf8Name), std::move(utf8Value));
        }
        if (name) CoTaskMemFree(name);
        if (value) CoTaskMemFree(value);
        if (FAILED(iterator->MoveNext(&hasCurrent))) break;
    }
    return result;
}

std::wstring ResponseContentType(ICoreWebView2WebResourceResponseView* response) {
    ComPtr<ICoreWebView2HttpResponseHeaders> headers;
    if (!response || FAILED(response->get_Headers(&headers)) || !headers) return {};
    LPWSTR contentType = nullptr;
    if (FAILED(headers->GetHeader(L"Content-Type", &contentType)) || !contentType) return {};
    std::wstring result(contentType);
    CoTaskMemFree(contentType);
    return Lower(std::move(result));
}

int MediaScore(const std::wstring& uri, const std::wstring& contentType, const HeaderMap& headers,
               std::string_view providerHost) {
    const auto lowerUri = Lower(uri);
    if (lowerUri.find(L"advert") != std::wstring::npos || lowerUri.find(L"preroll") != std::wstring::npos ||
        lowerUri.find(L"midroll") != std::wstring::npos || lowerUri.find(L"doubleclick") != std::wstring::npos ||
        lowerUri.find(L"adfinity") != std::wstring::npos || lowerUri.find(L"/vast") != std::wstring::npos ||
        lowerUri.find(L"cdn.plyr.io/") != std::wstring::npos || lowerUri.find(L"blank.mp4") != std::wstring::npos ||
        lowerUri.find(L"empty.mp4") != std::wstring::npos)
        return 0;

    int score = 0;
    if (lowerUri.find(L".m3u8") != std::wstring::npos) score = 130;
    else if (lowerUri.find(L".mpd") != std::wstring::npos) score = 120;
    else if (lowerUri.find(L".mp4") != std::wstring::npos) score = 100;
    if (contentType.find(L"mpegurl") != std::wstring::npos) score = std::max(score, 140);
    else if (contentType.find(L"dash+xml") != std::wstring::npos) score = std::max(score, 130);
    else if (contentType.find(L"video/mp4") != std::wstring::npos) score = std::max(score, 110);
    if (score == 0) return 0;

    bool providerContext = false;
    for (const auto& [name, value] : headers) {
        const auto lowerName = Lower(name);
        const auto lowerValue = Lower(value);
        if ((lowerName == "referer" || lowerName == "origin") &&
            lowerValue.find(providerHost) != std::string::npos) providerContext = true;
        if (lowerName == "authorizations" || lowerName == "accepts-controls") score += 30;
    }
    return providerContext ? score : 0;
}

std::string ProtocolFor(std::string_view uri, std::wstring_view contentType) {
    const auto lowerUri = Lower(std::string(uri));
    if (lowerUri.find(".mpd") != std::string::npos || contentType.find(L"dash+xml") != std::wstring::npos)
        return "dash";
    if (lowerUri.find(".mp4") != std::string::npos || contentType.find(L"video/mp4") != std::wstring::npos)
        return "http";
    return "hls";
}

bool IsSegmentRequest(std::wstring_view uri) {
    const auto lower = Lower(std::wstring(uri));
    return lower.find(L".m4s") != std::wstring::npos || lower.find(L".ts") != std::wstring::npos ||
           lower.find(L".cmfv") != std::wstring::npos || lower.find(L".cmfa") != std::wstring::npos ||
           lower.find(L".aac") != std::wstring::npos || lower.find(L".m4a") != std::wstring::npos;
}

struct BrowserSession final {
    std::string providerHost;
    std::wstring referer;
    std::wstring providerUrl;
    std::wstring userDataFolder;
    std::wstring injectionScript;
    ComPtr<ICoreWebView2Environment> environment;
    ComPtr<ICoreWebView2Controller> controller;
    ComPtr<ICoreWebView2> webView;
    bool wrapperInjected{false};
    bool collectMedia{false};
    std::string error;
    std::string mediaUrl;
    std::string protocol;
    HeaderMap headers;
    HeaderMap segmentHeaders;
    int mediaScore{0};
    std::chrono::steady_clock::time_point candidateTime{};

    void Fail(std::string message) {
        if (error.empty()) error = std::move(message);
    }

    void InspectResponse(ICoreWebView2WebResourceResponseReceivedEventArgs* arguments) {
        if (!collectMedia || !arguments) return;
        ComPtr<ICoreWebView2WebResourceRequest> request;
        ComPtr<ICoreWebView2WebResourceResponseView> response;
        if (FAILED(arguments->get_Request(&request)) || !request ||
            FAILED(arguments->get_Response(&response)) || !response) return;
        LPWSTR method = nullptr;
        if (FAILED(request->get_Method(&method)) || !method) return;
        const auto methodValue = Lower(std::wstring(method));
        CoTaskMemFree(method);
        if (methodValue != L"get") return;
        int status = 0;
        if (FAILED(response->get_StatusCode(&status)) || status < 200 || status >= 300) return;
        LPWSTR uri = nullptr;
        if (FAILED(request->get_Uri(&uri)) || !uri) return;
        const std::wstring uriValue(uri);
        CoTaskMemFree(uri);
        auto requestHeaders = ReadPlaybackHeaders(request.Get());
        const auto contentType = ResponseContentType(response.Get());
        if (protocol == "hls" && segmentHeaders.empty() && IsSegmentRequest(uriValue)) {
            const auto currentMedia = Url::Parse(mediaUrl);
            const auto segment = Url::Parse(WideToUtf8(uriValue));
            if (currentMedia && segment && currentMedia->Host() == segment->Host()) {
                segmentHeaders = requestHeaders;
                candidateTime = std::chrono::steady_clock::now();
            }
        }
        const int score = MediaScore(uriValue, contentType, requestHeaders, providerHost);
        if (score <= mediaScore) return;
        auto candidate = WideToUtf8(uriValue);
        const auto parsed = Url::Parse(candidate);
        if (!parsed || !parsed->IsHttps() || parsed->IsPrivateHostLiteral()) return;
        mediaScore = score;
        mediaUrl = std::move(candidate);
        protocol = ProtocolFor(mediaUrl, contentType);
        headers = std::move(requestHeaders);
        candidateTime = std::chrono::steady_clock::now();
    }
};

std::string HResultText(HRESULT result) {
    return std::format("0x{:08X}", static_cast<unsigned>(result));
}

void ConfigureWebView(BrowserSession& session) {
    ComPtr<ICoreWebView2Settings> settings;
    if (SUCCEEDED(session.webView->get_Settings(&settings)) && settings) {
        (void)settings->put_IsScriptEnabled(TRUE);
        (void)settings->put_AreDefaultScriptDialogsEnabled(FALSE);
        (void)settings->put_AreDefaultContextMenusEnabled(FALSE);
        (void)settings->put_AreDevToolsEnabled(FALSE);
        (void)settings->put_IsStatusBarEnabled(FALSE);
    }
    (void)session.webView->AddWebResourceRequestedFilter(L"*", COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL);

    EventRegistrationToken popupToken{};
    const auto popupHandler = Callback<ICoreWebView2NewWindowRequestedEventHandler>(
        [](ICoreWebView2*, ICoreWebView2NewWindowRequestedEventArgs* arguments) -> HRESULT {
            if (arguments) (void)arguments->put_Handled(TRUE);
            return S_OK;
        });
    if (FAILED(session.webView->add_NewWindowRequested(popupHandler.Get(), &popupToken))) {
        session.Fail("Unable to disable provider pop-up windows");
        return;
    }

    EventRegistrationToken permissionToken{};
    const auto permissionHandler = Callback<ICoreWebView2PermissionRequestedEventHandler>(
        [](ICoreWebView2*, ICoreWebView2PermissionRequestedEventArgs* arguments) -> HRESULT {
            if (arguments) (void)arguments->put_State(COREWEBVIEW2_PERMISSION_STATE_DENY);
            return S_OK;
        });
    if (FAILED(session.webView->add_PermissionRequested(permissionHandler.Get(), &permissionToken))) {
        session.Fail("Unable to deny provider browser permissions");
        return;
    }

    ComPtr<ICoreWebView2_2> webView2;
    if (FAILED(session.webView.As(&webView2)) || !webView2) {
        session.Fail("Installed WebView2 Runtime does not expose response inspection");
        return;
    }
    EventRegistrationToken responseToken{};
    const auto responseHandler = Callback<ICoreWebView2WebResourceResponseReceivedEventHandler>(
        [&session](ICoreWebView2*, ICoreWebView2WebResourceResponseReceivedEventArgs* arguments) -> HRESULT {
            session.InspectResponse(arguments);
            return S_OK;
        });
    if (FAILED(webView2->add_WebResourceResponseReceived(responseHandler.Get(), &responseToken))) {
        session.Fail("Unable to observe provider media requests");
        return;
    }

    EventRegistrationToken navigationToken{};
    const auto navigationHandler = Callback<ICoreWebView2NavigationCompletedEventHandler>(
        [&session](ICoreWebView2*, ICoreWebView2NavigationCompletedEventArgs* arguments) -> HRESULT {
            if (session.wrapperInjected) return S_OK;
            BOOL succeeded = FALSE;
            if (!arguments || FAILED(arguments->get_IsSuccess(&succeeded)) || !succeeded) {
                session.Fail("Provider referer page could not be loaded in WebView2");
                return S_OK;
            }
            session.wrapperInjected = true;
            session.collectMedia = true;
            const std::wstring script =
                L"document.documentElement.innerHTML='<head><meta charset=\\\"utf-8\\\"></head><body style=\\\"margin:0;background:#000\\\"></body>';"
                L"const frame=document.createElement('iframe');frame.src=" + JavaScriptString(WideToUtf8(session.providerUrl)) +
                L";frame.allow='autoplay; encrypted-media';frame.style='position:fixed;inset:0;width:100%;height:100%;border:0';"
                L"document.body.appendChild(frame);";
            const HRESULT executeResult = session.webView->ExecuteScript(script.c_str(), nullptr);
            if (FAILED(executeResult)) session.Fail("Unable to create the provider iframe");
            return S_OK;
        });
    if (FAILED(session.webView->add_NavigationCompleted(navigationHandler.Get(), &navigationToken))) {
        session.Fail("Unable to observe WebView2 navigation");
        return;
    }

    const auto scriptHandler = Callback<ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandler>(
        [&session](HRESULT errorCode, LPCWSTR scriptId) -> HRESULT {
            // WebView2 passes the script id as an [in] string owned by the callback
            // invocation. It must not be released by the client.
            (void)scriptId;
            if (FAILED(errorCode)) {
                session.Fail("Unable to initialize the provider browser adapter");
                return S_OK;
            }
            const HRESULT navigateResult = session.webView->Navigate(session.referer.c_str());
            if (FAILED(navigateResult)) session.Fail("Unable to navigate the provider referer page");
            return S_OK;
        });
    const HRESULT scriptResult = session.webView->AddScriptToExecuteOnDocumentCreated(
        session.injectionScript.c_str(), scriptHandler.Get());
    if (FAILED(scriptResult)) session.Fail("Unable to register the provider browser adapter");
}

ResolveResult ResolveWithWebView(const Url& provider, const Url& referer, const std::filesystem::path& userDataFolder,
                                 const ResolveContext& context) {
    std::error_code directoryError;
    std::filesystem::create_directories(userDataFolder, directoryError);
    if (directoryError)
        return {ResolveStatus::Failed, "browser-embed", "Unable to create the WebView2 cache directory", {}};
    const auto sessionProfile = SessionProfilePath(userDataFolder);
    std::filesystem::create_directories(sessionProfile, directoryError);
    if (directoryError)
        return {ResolveStatus::Failed, "browser-embed", "Unable to create the WebView2 session profile", {}};
    ScopedProfileFolder profileCleanup(sessionProfile);

    BrowserSession session;
    session.providerHost = provider.Host();
    session.providerUrl = Utf8ToWide(provider.Value());
    session.referer = Utf8ToWide(referer.Value());
    session.userDataFolder = sessionProfile.wstring();
    session.injectionScript = LR"JS((()=>{
const host=location.hostname.toLowerCase();
if(host==='kodikplayer.com'||host.endsWith('.kodikplayer.com')||host==='alloha.yani.tv'){
  const selectors=['.play_button','.vjs-big-play-button','.plyr__control--overlaid','button[aria-label="Play"]'];
  const timer=setInterval(()=>{
    for(const selector of selectors){const button=document.querySelector(selector);if(button)button.click();}
    const video=document.querySelector('video');if(video&&video.paused)video.play().catch(()=>{});
  },250);
  setTimeout(()=>clearInterval(timer),30000);
}
})();)JS";

    const HRESULT comResult = CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED);
    const bool uninitializeCom = SUCCEEDED(comResult);
    if (FAILED(comResult))
        return {ResolveStatus::Failed, "browser-embed", "Unable to initialize the WebView2 apartment", {}};

    HWND hostWindow = CreateWindowExW(WS_EX_TOOLWINDOW, L"STATIC", L"WannaViewer resolver", WS_POPUP,
                                      0, 0, 2, 2, nullptr, nullptr, GetModuleHandleW(nullptr), nullptr);
    if (!hostWindow) {
        if (uninitializeCom) CoUninitialize();
        return {ResolveStatus::Failed, "browser-embed", "Unable to create the WebView2 host window", {}};
    }

    const auto environmentHandler = Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
        [&session, hostWindow](HRESULT errorCode, ICoreWebView2Environment* environment) -> HRESULT {
            if (FAILED(errorCode) || !environment) {
                session.Fail("Microsoft Edge WebView2 Runtime is unavailable (" + HResultText(errorCode) + ')');
                return S_OK;
            }
            session.environment = environment;
            const auto controllerHandler = Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(
                [&session](HRESULT controllerError, ICoreWebView2Controller* controller) -> HRESULT {
                    if (FAILED(controllerError) || !controller) {
                        session.Fail("Unable to create the WebView2 provider controller (" +
                                     HResultText(controllerError) + ')');
                        return S_OK;
                    }
                    session.controller = controller;
                    // Keep a normal viewport even though the parent window is never
                    // shown. Several provider players defer their media pipeline for
                    // tiny or invisible WebView viewports.
                    RECT bounds{0, 0, 1280, 720};
                    (void)session.controller->put_Bounds(bounds);
                    (void)session.controller->put_IsVisible(TRUE);
                    if (FAILED(session.controller->get_CoreWebView2(&session.webView)) || !session.webView) {
                        session.Fail("Unable to create the WebView2 provider view");
                        return S_OK;
                    }
                    ConfigureWebView(session);
                    return S_OK;
                });
            const HRESULT createResult = environment->CreateCoreWebView2Controller(hostWindow, controllerHandler.Get());
            if (FAILED(createResult)) session.Fail("Unable to start the WebView2 provider controller");
            return S_OK;
        });
    const auto environmentOptions = Microsoft::WRL::Make<CoreWebView2EnvironmentOptions>();
    if (!environmentOptions ||
        FAILED(environmentOptions->put_AdditionalBrowserArguments(L"--autoplay-policy=no-user-gesture-required"))) {
        DestroyWindow(hostWindow);
        if (uninitializeCom) CoUninitialize();
        return {ResolveStatus::Failed, "browser-embed", "Unable to configure the WebView2 provider environment", {}};
    }
    const HRESULT environmentResult = CreateCoreWebView2EnvironmentWithOptions(
        nullptr, session.userDataFolder.c_str(), environmentOptions.Get(), environmentHandler.Get());
    if (FAILED(environmentResult))
        session.Fail("Microsoft Edge WebView2 Runtime is unavailable (" + HResultText(environmentResult) + ')');

    const auto started = std::chrono::steady_clock::now();
    while (session.error.empty() && std::chrono::steady_clock::now() - started < kResolutionTimeout &&
           !context.stopToken.stop_requested()) {
        MSG message{};
        while (PeekMessageW(&message, nullptr, 0, 0, PM_REMOVE)) {
            if (message.message == WM_QUIT) {
                session.Fail("WebView2 provider thread stopped unexpectedly");
                break;
            }
            TranslateMessage(&message);
            DispatchMessageW(&message);
        }
        if (!session.mediaUrl.empty() &&
            std::chrono::steady_clock::now() - session.candidateTime >= kCandidateSettleTime) break;
        (void)MsgWaitForMultipleObjectsEx(0, nullptr, 50, QS_ALLINPUT, MWMO_INPUTAVAILABLE);
    }

    if (session.controller) (void)session.controller->Close();
    session.webView.Reset();
    session.controller.Reset();
    session.environment.Reset();
    DestroyWindow(hostWindow);
    if (uninitializeCom) CoUninitialize();

    if (context.stopToken.stop_requested())
        return {ResolveStatus::Failed, "browser-embed", "Provider resolution was cancelled", {}};
    if (!session.error.empty()) return {ResolveStatus::Failed, "browser-embed", session.error, {}};
    if (session.mediaUrl.empty())
        return {ResolveStatus::Unsupported, "browser-embed",
                "The provider browser loaded, but no public HLS/DASH/MP4 request was observed", {}};
    for (auto& [name, value] : session.segmentHeaders)
        session.headers.insert_or_assign(std::move(name), std::move(value));

    if (const auto media = Url::Parse(session.mediaUrl)) {
        std::vector<std::string> headerNames;
        headerNames.reserve(session.headers.size());
        for (const auto& [name, value] : session.headers) {
            (void)value;
            headerNames.push_back(Lower(name));
        }
        std::ranges::sort(headerNames);
        std::string names;
        for (const auto& name : headerNames) {
            if (!names.empty()) names += ',';
            names += name;
        }
        context.logger.Write(LogLevel::Debug, "browser-embed",
                             "Captured " + session.protocol + " request for " + media->Host() +
                                 " with headers=" + names);
    }

    const std::string providerTitle = provider.HostIs("kodikplayer.com") ? "Kodik" : "Alloha";
    ResolveResult result{ResolveStatus::Resolved, "browser-embed", {}, {providerTitle + " stream", {}}};
    Season season{"default", "Default", {}};
    VoiceTrack voice{"default", "Default", {}};
    voice.episodes.push_back({"default", "Video",
                              {{std::move(session.mediaUrl), {}, "Auto", {}, std::move(session.protocol),
                                std::move(session.headers), false}}});
    season.voiceTracks.push_back(std::move(voice));
    result.entry.seasons.push_back(std::move(season));
    return result;
}

} // namespace

BrowserEmbedResolver::BrowserEmbedResolver(std::filesystem::path userDataFolder)
    : userDataFolder_(std::move(userDataFolder)) {}

bool BrowserEmbedResolver::CanHandle(const Url& url) const {
    return url.IsHttps() && (url.HostIs("kodikplayer.com") || url.HostIs("alloha.yani.tv"));
}

ResolveResult BrowserEmbedResolver::Resolve(const Url& url, const ResolveContext& context) const {
    const auto refererText = RefererFrom(context);
    const auto referer = Url::Parse(refererText);
    if (!referer || !IsAllowedReferer(*referer))
        return {ResolveStatus::Unsupported, "browser-embed",
                "Kodik/Alloha require the original AnimeGo or YummyAnime page as Referer", {}};
    return ResolveWithWebView(url, *referer, userDataFolder_, context);
}

} // namespace wannaviewer
